language: shell
dist: trusty
group: bluezone
os:
  - linux
services:
  - docker
env:
  global:
    # General
    - DOCKER_BUILDKIT="1"
    - BUILDKIT_PROGRESS="plain"
    - DOCKER_DEFAULT_PLATFORM="linux/amd64"
    # Images
    - BUNDLE_IMAGE="ibm-wazi-for-devspaces-operator-bundle"
    - BUNDLE_CONTEXT="./devspaces-operator-bundle"
    - BUNDLE_DOCKERFILE="${BUNDLE_CONTEXT}/wazi.bundle.Dockerfile"
install:
  - docker build -t ${BUNDLE_IMAGE}:travis -f ${BUNDLE_DOCKERFILE} ${BUNDLE_CONTEXT}
script: 
  - echo "Success!"
