language: shell
dist: trusty
group: bluezone
os:
  - linux
services:
  - docker
env:
  global:
    # General
    - DOCKER_BUILDKIT="1"
    - BUILDKIT_PROGRESS="plain"
    - DOCKER_DEFAULT_PLATFORM="linux/amd64"
    # Images
    - INDEX_IMAGE="ibm-wazi-for-devspaces-catalog"
    - INDEX_CONTEXT="./devspaces-operator-bundle"
    - INDEX_DOCKERFILE="${INDEX_CONTEXT}/wazi.index.Dockerfile"
    - BUNDLE_IMAGE="ibm-wazi-for-devspaces-operator-bundle"
    - BUNDLE_CONTEXT="./devspaces-operator-bundle"
    - BUNDLE_DOCKERFILE="${BUNDLE_CONTEXT}/wazi.bundle.Dockerfile"
before_install:
  - echo $DOCKER_KEY | docker login -u $DOCKER_USER --password-stdin registry.redhat.io
  # Index Image
  - touch ${INDEX_CONTEXT}/bundles.db
install:
  - docker build --tag ${INDEX_IMAGE}:travis --file ${INDEX_DOCKERFILE} ${INDEX_CONTEXT}
  - docker build --tag ${BUNDLE_IMAGE}:travis --file ${BUNDLE_DOCKERFILE} ${BUNDLE_CONTEXT}
script: 
  - echo "Success!"
