#
#  Copyright (c) 2018-2023 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-operator
  namespace: eclipse-che
  labels:
    app: che-operator
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: che-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: che-operator
        app.kubernetes.io/name: che
        app.kubernetes.io/instance: che
        app.kubernetes.io/part-of: che.eclipse.org
        app.kubernetes.io/component: che-operator
    spec:
      containers:
        - name: che-operator
          image: quay.io/eclipse/che-operator:3.8
          command:
            - /manager
          args:
            - --leader-elect
          imagePullPolicy: Always
          ports:
            - containerPort: 60000
              name: metrics
          env:
            - name: CHE_DEFAULT_SPEC_COMPONENTS_DASHBOARD_HEADERMESSAGE_TEXT
              value: ''
            - name: CHE_DEFAULT_SPEC_COMPONENTS_PLUGINREGISTRY_OPENVSXURL
              value: ''
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTCOMPONENTS
              value: '[{"name": "universal-developer-image", "container": {"image":
                "registry.redhat.io/devspaces/udi-rhel8@sha256:66e2147d3909568820ff436be5bcceb37f64f8b23796462504bc56cd3c663c9c"}}]'
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTEDITOR
              value: che-incubator/che-code/latest
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DISABLECONTAINERBUILDCAPABILITIES
              value: 'false'
            - name: CHE_FLAVOR
              value: devspaces
            - name: CHE_VERSION
              value: 3.8.0
            - name: CONSOLE_LINK_DISPLAY_NAME
              value: Eclipse Che
            - name: CONSOLE_LINK_IMAGE
              value: /dashboard/assets/branding/loader.svg
            - name: CONSOLE_LINK_NAME
              value: che
            - name: CONSOLE_LINK_SECTION
              value: Red Hat Applications
            - name: MAX_CONCURRENT_RECONCILES
              value: '1'
            - name: OPERATOR_NAME
              value: che-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_che__centos__mongodb_36_centos7_devfile_registry_image_NRQXIZLTOQWWCOJRGVSGEN3CMVRWCOBXGE4TQZTDMQ3TQNRQGA4DMOJYHFTGKODBGMZDOYJRME2GMNRVGA4DAMRVMI3DIYLCGI4GMY3DG42DEM3CGI______
              value: quay.io/eclipse/che--centos--mongodb-36-centos7@sha256:a915db7beca87198fcd7860086989fe8a327a1a4f6508025b64ab28fcc7423b2
            - name: RELATED_IMAGE_che__centos__mongodb_36_centos7_devfile_registry_image_NRQXIZLTOQWWMZTEMYZDIMZRMJRGGNTEHFQTSZBSMEYDGZJZGVRGEYTFHBQWIYRUHFQWEOLFMFRTGMBRMYZDMODBGM2TAMZYMM4DIMRYHAZDKOLDGE______
              value: quay.io/eclipse/che--centos--mongodb-36-centos7@sha256:ffdf2431bbc6d9a9d2a03e95bbbe8adb49ab9eac301f268a35038c84288259c1
            - name: RELATED_IMAGE_che__centos__mysql_57_centos7_devfile_registry_image_NRQXIZLTOQWWKMBYMVSTIZBUGNRDOMZVGY3DANZWHA2WENRZMJSGKNRTGM2WKMRXMNTDEMDDGAZDAZRTGQ2WENTDGZRTKOJUGAYDCOBTHA4DENZWGQ______
              value: quay.io/eclipse/che--centos--mysql-57-centos7@sha256:e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
            - name: RELATED_IMAGE_che__mariadb_devfile_registry_image_GEYC4NZOGEWTKYJYGAYDSMZWHFSWKNJXMM4DKYRWMY2GCMBYGQYDMMJUG5RGIOLDGUYDKY3EMU3GEOBSGUYGIMJWMEZDOZBSME2WMZLCMZSGKYLEG4______
              value: quay.io/eclipse/che--mariadb@sha256:5a8009369ee57c85b6f4a08406147bd9c505cde6b8250d16a27d2a5febfdead7
            - name: RELATED_IMAGE_che_code_devfile_registry_image_IBZWQYJSGU3DUNJSGI3TMZJQGZTGEMZYMY2GMNTDMM4GMM3GHE2TANRZMZSDOMZWMFSGMNRUHFRDQNLGMJSTAYZYGA4TEOJSGY3TQY3DG5RWIZBYHA2Q____
              value: quay.io/che-incubator/che-code@sha256:52276e06fb38f4f6cc8f3f95069fd736adf649b85fbe0c809292678cc7cdd885
            - name: RELATED_IMAGE_che_code_devfile_registry_image_NFXHG2LEMVZHG___
              value: quay.io/che-incubator/che-code@sha256:107b0d27a9fa291e258b7ee1693be795e399598b04c4ebf6fd824943854a5256
            - name: RELATED_IMAGE_che_code_plugin_registry_image_IBZWQYJSGU3DUNJSGI3TMZJQGZTGEMZYMY2GMNTDMM4GMM3GHE2TANRZMZSDOMZWMFSGMNRUHFRDQNLGMJSTAYZYGA4TEOJSGY3TQY3DG5RWIZBYHA2Q____
              value: quay.io/che-incubator/che-code@sha256:52276e06fb38f4f6cc8f3f95069fd736adf649b85fbe0c809292678cc7cdd885
            - name: RELATED_IMAGE_che_code_plugin_registry_image_NFXHG2LEMVZHG___
              value: quay.io/che-incubator/che-code@sha256:107b0d27a9fa291e258b7ee1693be795e399598b04c4ebf6fd824943854a5256
            - name: RELATED_IMAGE_che_editor_jupyter_plugin_registry_image_IBZWQYJSGU3DUOBTGQZTSYLFHFSWIY3BMEZWCOJXGUZTMNZUGIZTCNLBG44TCMTGHEZWKNBZHFTDIOJYGQ3WIYJQHE2GGNBYGAYDGMLFMFSTIYTBGQ3Q____
              value: index.docker.io/ksmster/che-editor-jupyter@sha256:83439ae9edcaa3a97536742315a7912f93e499f49847da094c480031eae4ba47
            - name: RELATED_IMAGE_che_idea_devfile_registry_image_NZSXQ5A_
              value: quay.io/che-incubator/che-idea@sha256:fffc242e7c740bec94570fb15d50022d2410910165105f2d4d7370fe6779ed14
            - name: RELATED_IMAGE_che_idea_plugin_registry_image_IBZWQYJSGU3DUODBMFSTMOLEMM2GEMDDGEZDENBZGFQTONJUGAYDMMZZMFTDAZTFHEZGENLFGIYTIYZWMU3DQYLDHE3WGZDBGI4WMYRVHBRDINBRGUYQ____
              value: quay.io/che-incubator/che-idea@sha256:8aae69dc4b0c122491a75400639af0fe92b5e214c6e68ac97cda29fb58b44151
            - name: RELATED_IMAGE_che_idea_plugin_registry_image_NZSXQ5A_
              value: quay.io/che-incubator/che-idea@sha256:fffc242e7c740bec94570fb15d50022d2410910165105f2d4d7370fe6779ed14
            - name: RELATED_IMAGE_che_pycharm_plugin_registry_image_IBZWQYJSGU3DUN3DGBSTGZLBMJSDMMRUHE2TEMBRMNTDKYTBGBQTSMJTG43TMZBZG4ZGCMLFGZTGEOLDMYYWEY3EMM3TQYLGMNTDIZBXGI2TMYLGGQ3Q____
              value: quay.io/che-incubator/che-pycharm@sha256:7c0e3eabd62495201cf5ba0a913776d972a1e6fb9cf1bcdc78afcf4d7256af47
            - name: RELATED_IMAGE_che_pycharm_plugin_registry_image_NZSXQ5A_
              value: quay.io/che-incubator/che-pycharm@sha256:40979e817d0523b5d9d32083a9502ce336a43bbda0ece2d1a85423ad886616e9
            - name: RELATED_IMAGE_che_server
              value: registry.redhat.io/devspaces/server-rhel8:3.8
            - name: RELATED_IMAGE_code_server_plugin_registry_image_IBZWQYJSGU3DUZLGGA3TEOBRGAYDIOJQHFRGEMTDGIZDQNBSGJSGMMTFHE4WCNLCME2WKNBVGBTGGZJXGU2DMYRYMZQTCOBWHA2TEZRSGNRGMNRXGUYQ____
              value: index.docker.io/codercom/code-server@sha256:ef07281004909bb2c228422df2e99a5ba5e450fce7546b8fa186852f23bf6751
            - name: RELATED_IMAGE_dashboard
              value: registry.redhat.io/devspaces/dashboard-rhel8:3.8
            - name: RELATED_IMAGE_devfile_registry
              value: registry.redhat.io/devspaces/devfileregistry-rhel8:3.8
            - name: RELATED_IMAGE_devworkspace_controller
              value: registry.redhat.io/devworkspace/devworkspace-rhel8-operator
            - name: RELATED_IMAGE_dirigible_openshift_plugin_registry_image_IBZWQYJSGU3DUMZTGY2TMMZVMQYWKMBUGAZTMOJXMRSWCMBWG42GEYTCMRRTONBZMM2GEZJSMRRDEOJYGE4GCOJTMI4GKMLFGUZWGM3DGUYTINBRGEZQ____
              value: index.docker.io/dirigiblelabs/dirigible-openshift@sha256:3365635d1e0403697dea0674bbbdc749c4be2db29818a93b8e1e53c3c5144113
            - name: RELATED_IMAGE_eclipse_broadway_plugin_registry_image_IBZWQYJSGU3DUNJXMM4DEY3EHAYDMYJVGZTDMOLBME4DMNRTMY3DQNBQGVSDANZXHBRDMMRYMEZDSYJWGRTGEMJWHA4DCYRRGFRWKOLGGQ4DIZDEME3Q____
              value: index.docker.io/wsskeleton/eclipse-broadway@sha256:57c82cd806a56f69aa8663f68405d0778b628a29a64fb16881b11ce9f484dda7
            - name: RELATED_IMAGE_gateway_authentication_sidecar
              value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12
            - name: RELATED_IMAGE_gateway_authorization_sidecar
              value: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
            - name: RELATED_IMAGE_plugin_registry
              value: registry.redhat.io/devspaces/pluginregistry-rhel8:3.8
            - name: RELATED_IMAGE_pvc_jobs
              value: registry.redhat.io/ubi8/ubi-minimal:8.8
            - name: RELATED_IMAGE_single_host_gateway
              value: registry.redhat.io/devspaces/traefik-rhel8:3.8
            - name: RELATED_IMAGE_single_host_gateway_config_sidecar
              value: registry.redhat.io/devspaces/configbump-rhel8:3.8
            - name: RELATED_IMAGE_ubi_minimal_devfile_registry_image_
              value: registry.access.redhat.com/ubi8/ubi-minimal@sha256:e52fc1de73dc2879516431ff1865e0fb61b1a32f57b6f914bdcddb13c62f84e6
            - name: RELATED_IMAGE_universal_developer_image_devfile_registry_image_IBZWQYJSGU3DUYZTGUYWIYTBHBRTEMBTGQ4TINJRGJQWCZJSGBSDSMJRGQ2GCMBYGQZWMNRYMU4DSN3GMJRTIY3FGAZDSNRZGM4WENBYMY2DSOBVGNSQ____
              value: quay.io/devfile/universal-developer-image@sha256:c351dba8c203494512aae20d91144a0843f68e897fbc4ce0296939b48f49853e
            - name: RELATED_IMAGE_universal_developer_image_devfile_registry_image_OVRGSOBNNRQXIZLTOQ______
              value: quay.io/devfile/universal-developer-image@sha256:c351dba8c203494512aae20d91144a0843f68e897fbc4ce0296939b48f49853e
            - name: RELATED_IMAGE_universal_developer_image_plugin_registry_image_IBZWQYJSGU3DUYZTGUYWIYTBHBRTEMBTGQ4TINJRGJQWCZJSGBSDSMJRGQ2GCMBYGQZWMNRYMU4DSN3GMJRTIY3FGAZDSNRZGM4WENBYMY2DSOBVGNSQ____
              value: quay.io/devfile/universal-developer-image@sha256:c351dba8c203494512aae20d91144a0843f68e897fbc4ce0296939b48f49853e
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: che-operator
      terminationGracePeriodSeconds: 20
