apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-openshift-monitoring-prometheus-k8s
  labels:
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/managed-by: olm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
