---
displayName: Java 11 with Quarkus
description: Java stack with OpenJDK 11, Maven 3.6 and Quarkus Tools
tags: ["Java", "OpenJDK", "Maven", "Quarkus", "UBI8"]
icon: /images/type-quarkus.svg
links:
  v2: https://github.com/devspaces-samples/quarkus-quickstarts/tree/devspaces-3.6-rhel-8
